# Generated by Django 5.1.2 on 2024-10-16 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verification_code", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Payment Intent ID",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказ",
            },
        ),
    ]
