# Generated by Django 5.1.2 on 2024-10-16 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название Сети"),
                ),
                ("prefix", models.CharField(max_length=2, verbose_name="Индикатор")),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="logo/", verbose_name="Логотип"
                    ),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Юридический Адрес",
                    ),
                ),
                (
                    "access_clients",
                    models.BooleanField(default=False, verbose_name="Доступ клиентам"),
                ),
            ],
            options={
                "verbose_name": "Сеть",
                "verbose_name_plural": "Сети",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkType",
            fields=[
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("furniture", "Мебель"),
                            ("technique", "Техника"),
                            ("build_materials", "Стройматериал"),
                            ("company", "Продуктовая компания"),
                        ],
                        default="furniture",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Тип сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип сети",
                "verbose_name_plural": "Типы сетей",
                "ordering": ["network_type"],
            },
        ),
    ]
