# Generated by Django 5.1.2 on 2024-10-16 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_network",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственное лицо",
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="network_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="networks_type",
                to="network.networktype",
                verbose_name="Тип сети",
            ),
        ),
    ]
