# Generated by Django 5.1.2 on 2024-10-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisabledAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disable",
                    models.BooleanField(default=False, verbose_name="Отключить API"),
                ),
            ],
            options={
                "verbose_name": "Временное отключение API",
                "verbose_name_plural": "Временное отключение API",
            },
        ),
    ]
