# mypy: ignore-errors
"""

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings_folder and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import django_stubs_ext

from beam.settings.base import *

django_stubs_ext.monkeypatch()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# THIRD_PARTY_APPS += ["debug_toolbar",]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS

# MIDDLEWARE += [  # type: ignore
#     "debug_toolbar.middleware.DebugToolbarMiddleware",
#     "debug_toolbar_force.middleware.ForceDebugToolbarMiddleware",
# ]

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#                 # "django.template.context_processors.debug",
#             ],
#         },
#     },
# ]

# Quick-start development settings_folder - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"},
        "x-api-key": {"type": "apiKey", "name": "x-api-key", "in": "header"},
    },
    "USE_SESSION_AUTH": False,
}

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda _request: DEBUG
}

INTERNAL_IPS = [
    "127.0.0.1",
]